services:
- type: web
  name: izumi-v3
  runtime: docker
  repo: https://bitbucket.org/izumi-eypz/izumi-v3
  plan: free
  envVars:
  - key: SUDO
    sync: false
  - key: SESSION_ID
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
