services:
  - type: web
    name: izumi-v3
    env: docker
    branch: main
    repo: https://github.com/sataniceypz/Izumi-v3.git
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: SUDO
        sync: false
      - key: MODE
        sync: false
